### ISSUE TITLE
Invalid tuple selector error hides others

### ISSUE THREAD

**Issue by RandomActsOfGrammar** [melt-umn/silver#845]
If we have
```
grammar x;

function f
Integer ::=
{
  return x.2;
}
```
where `x` is not defined, we get a single error:
```
Errors for x
 [../x/x.sv]
x.sv:6:9: error: Invalid tuple selector index.
```
While it is true the index is invalid, I'm more interested in knowing the reason it is invalid is that `x` is not defined.  That error is not showing up.

I'm not really sure how it is possible to get this error, assuming the tests are passing, as there is a [test](https://github.com/melt-umn/silver/blob/7318a1a69bc7cb273ef0a7e045ba86745ad64ef0/test/silver_features/Tuple.sv#L242-L250) specifically to catch this that was introduced in #505 that was a fix for #503.

**Comment by krame505** [comment]
@tardism it looks like the issue here is that when the tuple selector is out of bounds, we don't forward to a tree containing the `tuple` expression.  This can be fixed by including `tuple.errors` in the list of errors in the `errorExpr`.
